version: '3.8'

services:
  api:
    # Substitua pela URL exata do seu repositório ECR
    image: <sua-conta-aws>.dkr.ecr.<sua-regiao>.amazonaws.com/saas-logistica-api:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://usuario:senha@ip-do-banco:5432/saas_rentals
      - JWT_SECRET=sua_chave_padrao
      - PORT=3000

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      # Permite que o Watchtower controle o Docker da máquina
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # OBRIGATÓRIO: Avisa ao Watchtower para usar as credenciais da EC2
      - AWS_REGION=us-east-1 
    command: --interval 60 --cleanup